version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
    versioning-strategy: auto
    open-pull-requests-limit: 10
    # Security Advisories 
    security-advisories:
      allow: "security-advisories"
    # Dependency Updates 
    dependency-updates:
      allow: "security-updates"
